# Dataset name
DATASET_NAME: "$DATASET_NAME"
DATASET_DIR: "$DATASET_DIR"
# Model
MODEL: "$MODEL"
# Visual ecoder
VIS_ENCODER: "$VIS_ENCODER"
# Prompt template
PROMPT_TEMPLATE: 'imported in main.py'
# Seeed to separate train and validation
validation_seed: 0
# Ratio validation
ratio_train_val: 0.8
# Batch size
BATCH_SIZE: 8
# Set seeds
OPTIM_SEED: "$OPTIM_SEED"
# Classes split
CLASSES_SPLIT: SPLIT_SEED
# Seed split
SPLIT_SEED: "$SPLIT_SEED"
