MODEL: "coop_pseudo_baseline"
# Visual ecoder
VIS_ENCODER: "ViT-B/32"
# Prompt template
PROMPT_TEMPLATE: "a photo of a "
# Prefix size
PREFIX_SIZE: 16
N_PSEUDOSHOTS: 16
# Initialization mean and variance
MEAN_INIT: 0
VAR_INIT: 0.02
# Seeed to separate train and validation
validation_seed: 0
# Ratio validation
ratio_train_val: 0.2
# Batch size
BATCH_SIZE: 12
# Number of epochs
EPOCHS: 15
# Scheduler
SCHEDULER: "cosine"
# Scheduler warmup epochs
WARMUP_EPOCHS: 5
WARMUP_LR: 0.0001
# Number of accumulation iter
ACCUMULATION_ITER: 1
# Optimizer
OPTIM: "SGD"
LR: 0.1
DECAY: 0.1
STEP_SIZE: 1