from .fine_tune import FineTuneModule
from .prototype import PrototypeModule
from .transfer import TransferModule
from .multitask import MultiTaskModule
from .zsl_kg_lite import ZSLKGModule
from .dann import DannModule
from .fixmatch import FixMatchModule
from .naive_video import NaiveVideoModule
from .random import RandomModule
from .pseudoshots import PseudoShotModule
