# Travis CI config for taglets

dist: xenial
sudo: false
language: python
python:
  - "3.7"

cache:
  directories:
    - download
    - travis_wait 30 predefined

before_install:
  - travis_retry
    wget https://repo.continuum.io/miniconda/Miniconda3-4.5.1-Linux-x86_64.sh
    --output-document=download/miniconda.sh
  - bash download/miniconda.sh -b -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda config --set always_yes yes --set changeps1 no
  - conda info --all

install:
  - chmod u+x ./setup.sh
  - travis_retry ./setup.sh

script:
  - export PYTHONPATH=".:$PYTHONPATH"
  - accelerate launch --config_file ./accelerate_unittest_config.yml ./run_unittest.py

